services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - "8080:80"
    volumes:
      -  ./src:/var/www/html
    env_file:
      - ./.env
    networks:
      - default
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TEST
      MYSQL_USER: user
      MYSQL_PASSWORD: pw
    ports:
      -  "3306:3306"
    volumes:
      -  ./db/init:/docker-entrypoint-initdb.d
    networks:
      - default